from __future__ import annotations

__all__ = [
    "SESSION_VERSION",
    "SESSION_ALGORITHM",
    "DIRECT_MESSAGE_VERSION",
    "DIRECT_MESSAGE_TYPE",
    "DIRECT_MESSAGE_ALGORITHM",
    "HANDSHAKE_VERSION",
    "HANDSHAKE_ALGORITHM",
    "HANDSHAKE_INIT_TYPE",
    "HANDSHAKE_RESPONSE_TYPE",
    "DEFAULT_MAX_SKIP",
]

SESSION_VERSION = 1
SESSION_ALGORITHM = "mesh-direct-v1"

DIRECT_MESSAGE_VERSION = 1
DIRECT_MESSAGE_TYPE = "direct_message"
DIRECT_MESSAGE_ALGORITHM = "mesh-direct-v1"

HANDSHAKE_VERSION = 1
HANDSHAKE_ALGORITHM = "mesh-direct-v1"
HANDSHAKE_INIT_TYPE = "direct_handshake_init"
HANDSHAKE_RESPONSE_TYPE = "direct_handshake_response"

DEFAULT_MAX_SKIP = 600
